CRITICAL - 2021-06-14 10:30:41 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\framework\app\Views\usuarios\rol.php(44): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 44, Array)
#1 C:\xampp\htdocs\framework\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\framework\system\Common.php(1250): CodeIgniter\View\View->render('usuarios/rol', Array, true)
#4 C:\xampp\htdocs\framework\app\Controllers\Usuarios.php(137): view('usuarios/rol', Array)
#5 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Usuarios->rol('3')
#6 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#7 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-06-14 10:42:52 --> Call to a member function getDatos() on null
#0 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->cierre('1')
#1 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#2 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2021-06-14 10:43:16 --> Table 'codeigniter.cierre_caja' doesn't exist
CRITICAL - 2021-06-14 10:43:16 --> Call to a member function getResult() on bool
#0 C:\xampp\htdocs\framework\system\BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#1 C:\xampp\htdocs\framework\app\Controllers\Cajas.php(159): CodeIgniter\BaseModel->findAll()
#2 C:\xampp\htdocs\framework\app\Controllers\Cajas.php(149): App\Controllers\Cajas->getDatos('1')
#3 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->cierre('1')
#4 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#5 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2021-06-14 10:44:10 --> Table 'codeigniter.cierre_caja' doesn't exist
CRITICAL - 2021-06-14 10:44:10 --> Call to a member function getResult() on bool
#0 C:\xampp\htdocs\framework\system\BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#1 C:\xampp\htdocs\framework\app\Controllers\Cajas.php(159): CodeIgniter\BaseModel->findAll()
#2 C:\xampp\htdocs\framework\app\Controllers\Cajas.php(149): App\Controllers\Cajas->getDatos('2')
#3 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->cierre('2')
#4 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#5 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2021-06-14 10:44:19 --> Table 'codeigniter.cierre_caja' doesn't exist
CRITICAL - 2021-06-14 10:44:19 --> Call to a member function getResult() on bool
#0 C:\xampp\htdocs\framework\system\BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#1 C:\xampp\htdocs\framework\app\Controllers\Cajas.php(159): CodeIgniter\BaseModel->findAll()
#2 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->getDatos('1')
#3 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#4 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-06-14 10:47:11 --> Call to a member function join() on null
#0 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->getDatos('1')
#1 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#2 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2021-06-14 10:47:22 --> Table 'codeigniter.cierre_caja' doesn't exist
CRITICAL - 2021-06-14 10:47:22 --> Call to a member function getResult() on bool
#0 C:\xampp\htdocs\framework\system\BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#1 C:\xampp\htdocs\framework\app\Controllers\Cajas.php(158): CodeIgniter\BaseModel->findAll()
#2 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->getDatos('1')
#3 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#4 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#6 {main}
ERROR - 2021-06-14 10:48:24 --> Unknown column 'cierre_caja.id_caja' in 'where clause'
CRITICAL - 2021-06-14 10:48:24 --> Call to a member function getResult() on bool
#0 C:\xampp\htdocs\framework\system\BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#1 C:\xampp\htdocs\framework\app\Controllers\Cajas.php(158): CodeIgniter\BaseModel->findAll()
#2 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->getDatos('1')
#3 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#4 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-06-14 10:49:19 --> Invalid file: header.php
#0 C:\xampp\htdocs\framework\system\View\View.php(213): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('header.php')
#1 C:\xampp\htdocs\framework\system\Common.php(1250): CodeIgniter\View\View->render('header', Array, true)
#2 C:\xampp\htdocs\framework\app\Controllers\Cajas.php(150): view('header')
#3 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->cierre('2')
#4 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#5 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-06-14 10:56:24 --> Too few arguments to function App\Controllers\Cajas::cerrar(), 0 passed in C:\xampp\htdocs\framework\system\CodeIgniter.php on line 931 and exactly 1 expected
#0 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->cerrar()
#1 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#2 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-06-14 10:56:45 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\framework\app\Views\cajas\cierre.php(25): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\framework\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\framework\system\Common.php(1250): CodeIgniter\View\View->render('cajas/cierre', Array, true)
#4 C:\xampp\htdocs\framework\app\Controllers\Cajas.php(157): view('cajas/cierre')
#5 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->cerrar()
#6 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#7 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2021-06-14 11:02:11 --> Column 'id_caja' cannot be null
ERROR - 2021-06-14 11:07:07 --> Column 'id_caja' cannot be null
ERROR - 2021-06-14 11:07:16 --> Column 'id_caja' cannot be null
ERROR - 2021-06-14 11:08:57 --> Column 'id_caja' cannot be null
ERROR - 2021-06-14 11:10:48 --> Column 'id_caja' cannot be null
ERROR - 2021-06-14 11:10:56 --> Column 'id_caja' cannot be null
ERROR - 2021-06-14 11:13:16 --> Column 'id_caja' cannot be null
ERROR - 2021-06-14 11:14:31 --> Column 'id_caja' cannot be null
CRITICAL - 2021-06-14 11:30:05 --> Call to a member function select() on null
#0 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->cerrar('1')
#1 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#2 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2021-06-14 11:30:37 --> Unknown column 'fecha_alta' in 'where clause'
CRITICAL - 2021-06-14 11:30:37 --> Call to a member function getFirstRow() on bool
#0 C:\xampp\htdocs\framework\system\BaseModel.php(644): CodeIgniter\Model->doFirst()
#1 C:\xampp\htdocs\framework\app\Controllers\Cajas.php(168): CodeIgniter\BaseModel->first()
#2 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->cerrar('1')
#3 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#4 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-06-14 11:31:57 --> Call to a member function where() on null
#0 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->cerrar('1')
#1 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#2 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-06-14 11:45:50 --> Too few arguments to function App\Controllers\Cajas::cierre(), 0 passed in C:\xampp\htdocs\framework\system\CodeIgniter.php on line 931 and exactly 1 expected
#0 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->cierre()
#1 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#2 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-06-14 11:46:25 --> Too few arguments to function App\Controllers\Cajas::cierre(), 0 passed in C:\xampp\htdocs\framework\system\CodeIgniter.php on line 931 and exactly 1 expected
#0 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->cierre()
#1 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#2 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-06-14 12:06:10 --> Call to undefined method CodeIgniter\Session\Session::id_caja()
#0 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->abrir()
#1 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#2 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-06-14 12:57:19 --> Too few arguments to function App\Controllers\Cajas::cierre(), 0 passed in C:\xampp\htdocs\framework\system\CodeIgniter.php on line 931 and exactly 1 expected
#0 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->cierre()
#1 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#2 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2021-06-14 12:58:44 --> Unknown column 'estado' in 'where clause'
CRITICAL - 2021-06-14 12:58:44 --> Call to a member function getFirstRow() on bool
#0 C:\xampp\htdocs\framework\system\BaseModel.php(644): CodeIgniter\Model->doFirst()
#1 C:\xampp\htdocs\framework\app\Controllers\Cajas.php(187): CodeIgniter\BaseModel->first()
#2 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->registrarCajaCierre()
#3 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#4 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#6 {main}
ERROR - 2021-06-14 12:59:45 --> Unknown column 'estado' in 'where clause'
CRITICAL - 2021-06-14 12:59:45 --> Call to a member function getFirstRow() on bool
#0 C:\xampp\htdocs\framework\system\BaseModel.php(644): CodeIgniter\Model->doFirst()
#1 C:\xampp\htdocs\framework\app\Controllers\Cajas.php(187): CodeIgniter\BaseModel->first()
#2 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->registrarCajaCierre()
#3 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#4 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#6 {main}
ERROR - 2021-06-14 13:03:54 --> Unknown column 'staus' in 'where clause'
CRITICAL - 2021-06-14 13:03:54 --> Call to a member function getFirstRow() on bool
#0 C:\xampp\htdocs\framework\system\BaseModel.php(644): CodeIgniter\Model->doFirst()
#1 C:\xampp\htdocs\framework\app\Controllers\Cajas.php(175): CodeIgniter\BaseModel->first()
#2 C:\xampp\htdocs\framework\app\Controllers\Cajas.php(167): App\Controllers\Cajas->verficarCaja('2')
#3 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->cerrar('2')
#4 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#5 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2021-06-14 13:10:19 --> Column 'id_usuario' in where clause is ambiguous
CRITICAL - 2021-06-14 13:10:19 --> Call to a member function getFirstRow() on bool
#0 C:\xampp\htdocs\framework\system\BaseModel.php(644): CodeIgniter\Model->doFirst()
#1 C:\xampp\htdocs\framework\app\Controllers\Cajas.php(178): CodeIgniter\BaseModel->first()
#2 C:\xampp\htdocs\framework\app\Controllers\Cajas.php(168): App\Controllers\Cajas->verficarCaja('1')
#3 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->cerrar()
#4 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#5 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-06-14 13:11:19 --> Too few arguments to function CodeIgniter\Database\BaseBuilder::join(), 1 passed in C:\xampp\htdocs\framework\system\Model.php on line 800 and at least 2 expected
#0 C:\xampp\htdocs\framework\system\Model.php(800): CodeIgniter\Database\BaseBuilder->join('caja_cierre.sta...')
#1 C:\xampp\htdocs\framework\app\Controllers\Cajas.php(178): CodeIgniter\Model->__call('join', Array)
#2 C:\xampp\htdocs\framework\app\Controllers\Cajas.php(168): App\Controllers\Cajas->verficarCaja('1')
#3 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->cerrar()
#4 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#5 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2021-06-14 13:11:30 --> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '1)
WHERE `id_usuario` = '1'
AND DATE(fecha) = '2021-06-14'
AND `estado` = 1
 ...' at line 3
CRITICAL - 2021-06-14 13:11:30 --> Call to a member function getFirstRow() on bool
#0 C:\xampp\htdocs\framework\system\BaseModel.php(644): CodeIgniter\Model->doFirst()
#1 C:\xampp\htdocs\framework\app\Controllers\Cajas.php(178): CodeIgniter\BaseModel->first()
#2 C:\xampp\htdocs\framework\app\Controllers\Cajas.php(168): App\Controllers\Cajas->verficarCaja('1')
#3 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Cajas->cerrar()
#4 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
#5 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2021-06-14 13:38:15 --> Duplicate entry '97897889' for key 'codigo'
ERROR - 2021-06-14 13:40:04 --> Duplicate entry '97897800000' for key 'codigo'
CRITICAL - 2021-06-14 13:47:46 --> Invalid file: productos/editar/1.php
#0 C:\xampp\htdocs\framework\system\View\View.php(213): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('productos/edita...')
#1 C:\xampp\htdocs\framework\system\Common.php(1250): CodeIgniter\View\View->render('productos/edita...', Array, true)
#2 C:\xampp\htdocs\framework\app\Controllers\Productos.php(210): view('productos/edita...', Array)
#3 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Productos->actualizar()
#4 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Productos))
#5 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-06-14 20:03:25 --> syntax error, unexpected end of file
#0 C:\xampp\htdocs\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#1 C:\xampp\htdocs\framework\system\Common.php(1250): CodeIgniter\View\View->render('usuarios/rol', Array, true)
#2 C:\xampp\htdocs\framework\app\Controllers\Usuarios.php(142): view('usuarios/rol', Array)
#3 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Usuarios->rol('3')
#4 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#5 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2021-06-14 20:24:32 --> Column 'id_usuario' cannot be null
ERROR - 2021-06-14 21:06:58 --> Unknown column 'activo' in 'where clause'
ERROR - 2021-06-14 21:06:58 --> Unknown column 'activo' in 'where clause'
ERROR - 2021-06-14 21:06:58 --> Unknown column 'activo' in 'where clause'
ERROR - 2021-06-14 21:06:58 --> Unknown column 'activo' in 'where clause'
ERROR - 2021-06-14 21:06:58 --> Unknown column 'activo' in 'where clause'
ERROR - 2021-06-14 21:06:58 --> Unknown column 'activo' in 'where clause'
ERROR - 2021-06-14 21:25:25 --> Unknown column 'inventariable' in 'where clause'
CRITICAL - 2021-06-14 21:25:25 --> Call to a member function getResult() on bool
#0 C:\xampp\htdocs\framework\system\BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#1 C:\xampp\htdocs\framework\app\Controllers\Admin.php(153): CodeIgniter\BaseModel->findAll()
#2 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Admin->grafico()
#3 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#4 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#6 {main}
ERROR - 2021-06-14 21:26:22 --> Unknown column 'inventariable' in 'where clause'
CRITICAL - 2021-06-14 21:26:22 --> Call to a member function getResult() on bool
#0 C:\xampp\htdocs\framework\system\BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#1 C:\xampp\htdocs\framework\app\Controllers\Admin.php(153): CodeIgniter\BaseModel->findAll()
#2 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Admin->grafico()
#3 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#4 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#6 {main}
ERROR - 2021-06-14 21:27:07 --> Unknown column 'inventariable' in 'where clause'
CRITICAL - 2021-06-14 21:27:07 --> Call to a member function getResult() on bool
#0 C:\xampp\htdocs\framework\system\BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#1 C:\xampp\htdocs\framework\app\Controllers\Admin.php(153): CodeIgniter\BaseModel->findAll()
#2 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Admin->grafico()
#3 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#4 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-06-14 21:42:15 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\framework\app\Views\usuarios\perfil.php(49): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 49, Array)
#1 C:\xampp\htdocs\framework\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\framework\system\Common.php(1250): CodeIgniter\View\View->render('usuarios/perfil', Array, true)
#4 C:\xampp\htdocs\framework\app\Controllers\Usuarios.php(327): view('usuarios/perfil')
#5 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Usuarios->perfil()
#6 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#7 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-06-14 22:05:38 --> getimagesize(http://localhost/framework/public/images/logo.jpg): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found

#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'getimagesize(ht...', 'C:\\xampp\\htdocs...', 1238, Array)
#1 C:\xampp\htdocs\framework\app\Libraries\fpdf\fpdf.php(1238): getimagesize('http://localhos...')
#2 C:\xampp\htdocs\framework\app\Libraries\fpdf\fpdf.php(885): FPDF->_parsejpg('http://localhos...')
#3 C:\xampp\htdocs\framework\app\Controllers\Admin.php(166): FPDF->Image('http://localhos...', 10, 5, 30, 30, 'jpg')
#4 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Admin->minimo()
#5 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#6 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-06-14 22:06:10 --> getimagesize(http://localhost/framework/public/images/logo.jpg): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found

#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'getimagesize(ht...', 'C:\\xampp\\htdocs...', 1238, Array)
#1 C:\xampp\htdocs\framework\app\Libraries\fpdf\fpdf.php(1238): getimagesize('http://localhos...')
#2 C:\xampp\htdocs\framework\app\Libraries\fpdf\fpdf.php(885): FPDF->_parsejpg('http://localhos...')
#3 C:\xampp\htdocs\framework\app\Controllers\Admin.php(166): FPDF->Image('http://localhos...', 10, 5, 30, 30, 'jpg')
#4 C:\xampp\htdocs\framework\system\CodeIgniter.php(931): App\Controllers\Admin->minimo()
#5 C:\xampp\htdocs\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#6 C:\xampp\htdocs\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\framework\public\index.php(36): CodeIgniter\CodeIgniter->run()
#8 {main}
